### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by dakar91**
Standardised most models with local testing files and readme, as well as consolidated a list of examples in the main repo readme. 

All models in the readme table have been tested locally and work as expected.

### CODE REVIEW

**Comment by pavelklushin** [comment]
Please add in the Financial text generation that it's fine tuned on financial data

**Comment by guyeshet** [comment]
amazing work @dakar91 !

**Comment by pavelklushin** [comment]
@guyeshet once this will be ready let's add it to the notebooks as "Qwak examples" folder

**Review by pavelklushin — COMMENTED** [review]
lgtm

**Comment by guyeshet** [comment]
Sounds great to me

**Pull request merged**
